name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore NoitaMap/NoitaMap.csproj
      - name: Build
        run: dotnet build NoitaMap/NoitaMap.csproj --no-restore 
      - name: Publish
        run: |
          dotnet publish NoitaMap/NoitaMap.csproj -r win-x64 -p:PublishSingleFile=true --self-contained true -o ~/win-x64
          dotnet publish NoitaMap/NoitaMap.csproj -r linux-x64 -p:PublishSingleFile=true --self-contained true -o ~/linux-x64

      - name: Upload windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: |
            ~/win-x64/

      - name: Upload linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: |
            ~/linux-x64/
